version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    allow:
      - dependency-type: all
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    cooldown:
      default-days: 2
