packages:
  - packages/*
  - apps/*
  - examples/*

allowBuilds:
  esbuild: false
  unrs-resolver: false

catalog:
  '@vitest/coverage-v8': ^4.1.7
  jsdom: ^29.1.1
  vite: ^7.3.5
  vite-plugin-dts: ^5.0.1
  vitest: ^4.1.7

minimumReleaseAge: 2880 # 2 days
minimumReleaseAgeExclude:
  - '@orfium/*'
