sonar.projectKey=Orfium_orfium-ictinus
sonar.organization=orfium
sonar.sourceEncoding=UTF-8

sonar.sources=packages/ictinus/src

sonar.tests=packages/ictinus/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.tests.ts,**/*.tests.tsx

sonar.exclusions=**/__snapshots__/**,**/*.stories.tsx,**/*.mdx,**/*.css.ts
sonar.coverage.exclusions=**/test/**,**/*.test.*,**/*.tests.*,**/*.stories.tsx,**/*.mdx,**/*.style.ts,**/*.styles.ts,**/*.css.ts,**/*.tokens.ts

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
