import {
  AccountIcon,
  AlbumIcon,
  AnalyticsIcon,
  AppsIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArtistIcon,
  AssetIcon,
  AudioIcon,
  AudioOffIcon,
  BookmarkIcon,
  BookmarkOffIcon,
  BroadcastIcon,
  CalendarIcon,
  CatalogIcon,
  ChannelIcon,
  ChatIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CinemaIcon,
  ClaimIcon,
  CloseIcon,
  ColumnChooserIcon,
  CompositionIcon,
  ConcertIcon,
  ConflictIcon,
  ConvertIcon,
  CopyIcon,
  CueSheetIcon,
  DashboardIcon,
  DatasetIcon,
  DeleteIcon,
  DeliveryIcon,
  DetailsIcon,
  DigitalIcon,
  DistributionIcon,
  DownloadIcon,
  EarningsIcon,
  EditIcon,
  EntitiesIcon,
  ErrorIcon,
  ExternalLinkIcon,
  EyeIcon,
  EyeOffIcon,
  FavoriteIcon,
  FavoriteOffIcon,
  FileIcon,
  FilterIcon,
  FlagIcon,
  FlagOffIcon,
  ForwardIcon,
  FreezeIcon,
  HelpIcon,
  ImageIcon,
  ImageOffIcon,
  IncomeIcon,
  InformationalIcon,
  InsightIcon,
  InvoiceIcon,
  IssueIcon,
  KeywordIcon,
  LanguageIcon,
  LegalIcon,
  LicenseIcon,
  LinkIcon,
  LocationIcon,
  LockIcon,
  LoginIcon,
  LogoutIcon,
  MailIcon,
  ManualIcon,
  MediaFileIcon,
  MenuIcon,
  MinusIcon,
  MoreOptionsIcon,
  NextIcon,
  NotificationIcon,
  OrganizationIcon,
  PageFirstIcon,
  PageLastIcon,
  PairIcon,
  PauseIcon,
  PendingIcon,
  PlaycountIcon,
  PlayIcon,
  PlusIcon,
  PolicyIcon,
  PreviousIcon,
  PublicPerformanceIcon,
  PublisherIcon,
  RadioIcon,
  RecordingIcon,
  RecordLabelIcon,
  RedoIcon,
  RefreshIcon,
  ReportIcon,
  RestoreIcon,
  ResumeIcon,
  ReviewIcon,
  RewindIcon,
  RoleIcon,
  SearchFilledIcon,
  SearchIcon,
  SettingsIcon,
  ShareIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SortIcon,
  StatusIndicatorIcon,
  StopIcon,
  SuccessIcon,
  TagIcon,
  TelevisionIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleUpIcon,
  UndoIcon,
  UnfreezeIcon,
  UnlinkIcon,
  UnlockIcon,
  UnpairIcon,
  UnverifiedIcon,
  UpdateIcon,
  UploadIcon,
  UsageIcon,
  UserIcon,
  UsersIcon,
  VerifiedIcon,
  VideoIcon,
  VideoOffIcon,
  WarningIcon,
  WorkIcon,
  WriterIcon,
  YouTubeIcon,
} from '../icons';
import { type BoxProps } from '../vanilla/Box';

export type IconProps = {
  name: keyof typeof ICONS;
  size?: 'xs' | 'sm' | 'md' | 'lg';
} & Omit<BoxProps, 'size'>;

const SIZE = {
  xs: '3',
  sm: '4',
  md: '5',
  lg: '6',
} as const;

export function Icon({ name, size = 'md', ...props }: IconProps) {
  const IconComponent = ICONS[name];

  return <IconComponent size={SIZE[size]} {...props} />;
}

export const ICONS = {
  account: AccountIcon,
  album: AlbumIcon,
  analytics: AnalyticsIcon,
  apps: AppsIcon,
  arrowDown: ArrowDownIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  arrowUp: ArrowUpIcon,
  artist: ArtistIcon,
  asset: AssetIcon,
  audio: AudioIcon,
  audioOff: AudioOffIcon,
  bookmark: BookmarkIcon,
  bookmarkOff: BookmarkOffIcon,
  broadcast: BroadcastIcon,
  calendar: CalendarIcon,
  chat: ChatIcon,
  check: CheckIcon,
  catalog: CatalogIcon,
  channel: ChannelIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  cinema: CinemaIcon,
  claim: ClaimIcon,
  close: CloseIcon,
  columnChooser: ColumnChooserIcon,
  convert: ConvertIcon,
  composition: CompositionIcon,
  concert: ConcertIcon,
  conflict: ConflictIcon,
  copy: CopyIcon,
  cueSheet: CueSheetIcon,
  dashboard: DashboardIcon,
  dataset: DatasetIcon,
  delete: DeleteIcon,
  digital: DigitalIcon,
  distribution: DistributionIcon,
  delivery: DeliveryIcon,
  details: DetailsIcon,
  download: DownloadIcon,
  earnings: EarningsIcon,
  edit: EditIcon,
  entities: EntitiesIcon,
  error: ErrorIcon,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  externalLink: ExternalLinkIcon,
  favorite: FavoriteIcon,
  favoriteOff: FavoriteOffIcon,
  file: FileIcon,
  filter: FilterIcon,
  flag: FlagIcon,
  flagOff: FlagOffIcon,
  freeze: FreezeIcon,
  forward: ForwardIcon,
  help: HelpIcon,
  income: IncomeIcon,
  image: ImageIcon,
  imageOff: ImageOffIcon,
  informational: InformationalIcon,
  insight: InsightIcon,
  invoice: InvoiceIcon,
  issue: IssueIcon,
  keyword: KeywordIcon,
  language: LanguageIcon,
  legal: LegalIcon,
  license: LicenseIcon,
  link: LinkIcon,
  lock: LockIcon,
  location: LocationIcon,
  login: LoginIcon,
  logout: LogoutIcon,
  mail: MailIcon,
  manual: ManualIcon,
  mediaFile: MediaFileIcon,
  menu: MenuIcon,
  minus: MinusIcon,
  moreOptions: MoreOptionsIcon,
  next: NextIcon,
  notification: NotificationIcon,
  organization: OrganizationIcon,
  pageFirst: PageFirstIcon,
  pageLast: PageLastIcon,
  pair: PairIcon,
  pause: PauseIcon,
  pending: PendingIcon,
  playcount: PlaycountIcon,
  play: PlayIcon,
  plus: PlusIcon,
  publicPerformance: PublicPerformanceIcon,
  publisher: PublisherIcon,
  policy: PolicyIcon,
  previous: PreviousIcon,
  redo: RedoIcon,
  radio: RadioIcon,
  recording: RecordingIcon,
  recordLabel: RecordLabelIcon,
  refresh: RefreshIcon,
  report: ReportIcon,
  restore: RestoreIcon,
  resume: ResumeIcon,
  rewind: RewindIcon,
  review: ReviewIcon,
  role: RoleIcon,
  search: SearchIcon,
  searchFilled: SearchFilledIcon,
  settings: SettingsIcon,
  share: ShareIcon,
  sort: SortIcon,
  sortAscending: SortAscendingIcon,
  sortDescending: SortDescendingIcon,
  statusIndicator: StatusIndicatorIcon,
  stop: StopIcon,
  success: SuccessIcon,
  tag: TagIcon,
  television: TelevisionIcon,
  thumbsDown: ThumbsDownIcon,
  thumbsUp: ThumbsUpIcon,
  trendingDown: TrendingDownIcon,
  trendingUp: TrendingUpIcon,
  triangleDown: TriangleDownIcon,
  triangleLeft: TriangleLeftIcon,
  triangleRight: TriangleRightIcon,
  triangleUp: TriangleUpIcon,
  undo: UndoIcon,
  unfreeze: UnfreezeIcon,
  unlink: UnlinkIcon,
  unlock: UnlockIcon,
  unpair: UnpairIcon,
  unverified: UnverifiedIcon,
  update: UpdateIcon,
  upload: UploadIcon,
  usage: UsageIcon,
  user: UserIcon,
  users: UsersIcon,
  verified: VerifiedIcon,
  video: VideoIcon,
  videoOff: VideoOffIcon,
  warning: WarningIcon,
  work: WorkIcon,
  writer: WriterIcon,
  youTube: YouTubeIcon,
} as const;
