import {
  AccountIcon,
  AnalyticsIcon,
  AppsIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  CalendarIcon,
  ChatIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CloseIcon,
  ColumnChooserIcon,
  ConvertIcon,
  CopyIcon,
  DashboardIcon,
  DatasetIcon,
  DeleteIcon,
  DeliveryIcon,
  DetailsIcon,
  DownloadIcon,
  EarningsIcon,
  EditIcon,
  EntitiesIcon,
  ErrorIcon,
  ExternalLinkIcon,
  FileIcon,
  FilterIcon,
  HelpIcon,
  IncomeIcon,
  InformationalIcon,
  InsightIcon,
  InvoiceIcon,
  IssueIcon,
  KeywordIcon,
  LanguageIcon,
  LegalIcon,
  LocationIcon,
  LoginIcon,
  LogoutIcon,
  MailIcon,
  ManualIcon,
  MediaFileIcon,
  MenuIcon,
  MinusIcon,
  MoreOptionsIcon,
  NotificationIcon,
  OrganizationIcon,
  PageFirstIcon,
  PageLastIcon,
  PendingIcon,
  PlusIcon,
  PolicyIcon,
  RedoIcon,
  RefreshIcon,
  ReportIcon,
  RestoreIcon,
  ReviewIcon,
  RoleIcon,
  SearchFilledIcon,
  SearchIcon,
  SettingsIcon,
  ShareIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SortIcon,
  StatusIndicatorIcon,
  SuccessIcon,
  TagIcon,
  ThumbsDownIcon,
  ThumbsUpIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleUpIcon,
  UndoIcon,
  UnverifiedIcon,
  UpdateIcon,
  UploadIcon,
  UserIcon,
  UsersIcon,
  VerifiedIcon,
  WarningIcon,
} from '../icons';
import { type BoxProps } from '../vanilla/Box';

export type IconProps = {
  name: keyof typeof ICONS;
  size?: 'xs' | 'sm' | 'md' | 'lg';
} & Omit<BoxProps, 'size'>;

const SIZE = {
  xs: '3',
  sm: '4',
  md: '5',
  lg: '6',
} as const;

export function Icon({ name, size = 'md', ...props }: IconProps) {
  const IconComponent = ICONS[name];

  return <IconComponent size={SIZE[size]} {...props} />;
}

export const ICONS = {
  account: AccountIcon,
  analytics: AnalyticsIcon,
  apps: AppsIcon,
  arrowDown: ArrowDownIcon,
  arrowLeft: ArrowLeftIcon,
  arrowRight: ArrowRightIcon,
  arrowUp: ArrowUpIcon,
  calendar: CalendarIcon,
  chat: ChatIcon,
  check: CheckIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  close: CloseIcon,
  columnChooser: ColumnChooserIcon,
  convert: ConvertIcon,
  copy: CopyIcon,
  dashboard: DashboardIcon,
  dataset: DatasetIcon,
  delete: DeleteIcon,
  delivery: DeliveryIcon,
  details: DetailsIcon,
  download: DownloadIcon,
  earnings: EarningsIcon,
  edit: EditIcon,
  entities: EntitiesIcon,
  error: ErrorIcon,
  externalLink: ExternalLinkIcon,
  file: FileIcon,
  filter: FilterIcon,
  help: HelpIcon,
  income: IncomeIcon,
  informational: InformationalIcon,
  insight: InsightIcon,
  invoice: InvoiceIcon,
  issue: IssueIcon,
  keyword: KeywordIcon,
  language: LanguageIcon,
  legal: LegalIcon,
  location: LocationIcon,
  login: LoginIcon,
  logout: LogoutIcon,
  mail: MailIcon,
  manual: ManualIcon,
  mediaFile: MediaFileIcon,
  menu: MenuIcon,
  minus: MinusIcon,
  moreOptions: MoreOptionsIcon,
  notification: NotificationIcon,
  organization: OrganizationIcon,
  pageFirst: PageFirstIcon,
  pageLast: PageLastIcon,
  pending: PendingIcon,
  plus: PlusIcon,
  policy: PolicyIcon,
  redo: RedoIcon,
  refresh: RefreshIcon,
  report: ReportIcon,
  restore: RestoreIcon,
  review: ReviewIcon,
  role: RoleIcon,
  search: SearchIcon,
  searchFilled: SearchFilledIcon,
  settings: SettingsIcon,
  share: ShareIcon,
  sort: SortIcon,
  sortAscending: SortAscendingIcon,
  sortDescending: SortDescendingIcon,
  statusIndicator: StatusIndicatorIcon,
  success: SuccessIcon,
  tag: TagIcon,
  thumbsDown: ThumbsDownIcon,
  thumbsUp: ThumbsUpIcon,
  trendingDown: TrendingDownIcon,
  trendingUp: TrendingUpIcon,
  triangleDown: TriangleDownIcon,
  triangleLeft: TriangleLeftIcon,
  triangleRight: TriangleRightIcon,
  triangleUp: TriangleUpIcon,
  undo: UndoIcon,
  unverified: UnverifiedIcon,
  update: UpdateIcon,
  upload: UploadIcon,
  user: UserIcon,
  users: UsersIcon,
  verified: VerifiedIcon,
  warning: WarningIcon,
} as const;
