name: 'Visual'

on:
  pull_request:
    branches: [master]
    types: [labeled]
  push:
    branches: [master]

jobs:
  chromatic:
    if: ${{ github.event_name == 'push' || github.event.label.name == 'visual' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 #v6.0.10

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with:
          cache: pnpm
          node-version-file: package.json

      - run: |
          pnpm install
          pnpm build

      - uses: chromaui/action@14cfaef73576e69f95f47f60058063f46ca38719 #v18.1.0
        with:
          onlyChanged: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: apps/storybook/dist
          storybookBaseDir: apps/storybook
          autoAcceptChanges: 'master'
        env:
          STORYBOOK_ENV: true
