name: 'Visual'

on:
  pull_request:
    branches: [master]
    types: [labeled]
  push:
    branches: [master]

jobs:
  chromatic:
    if: ${{ github.event.label.name == 'visual' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: package.json

      - run: |
          pnpm install
          pnpm build

      - uses: chromaui/action@latest
        with:
          onlyChanged: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: apps/storybook/dist
          storybookBaseDir: apps/storybook
        env:
          STORYBOOK_ENV: true
