name: CI
on:
  push:
    branches:
      - 'master'
      - 'staging'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Push to Staging
        if: (github.ref == 'refs/heads/staging')
        run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/ictinus-staging.git HEAD:master
      - name: Push to Production
        if: (github.ref == 'refs/heads/master')
        run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/ictinus.git HEAD:master
