name: CI
on:
  push:
    branches:
      - 'master'
      - 'next'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Push to Production
        if: (github.ref == 'refs/heads/master')
        run: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/ictinus.git HEAD:master

      - name: Install dependencies
        run: yarn install

      - name: Release
        env:
          GITHUB_NPM_CONFIG_REGISTRY: 'https://npm.pkg.github.com/'
          GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLIC_NPM_CONFIG_REGISTRY: 'https://registry.npmjs.org'
          PUBLIC_NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
