# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js (12.16.2)
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.2'

    - name: Install Pacakges 
      run: npm ci
      
    - name: Build Step 
      env: 
        CI: "" 
      run: npm run build
      
    - name: Store Artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build

    - name: Run Semantic Release
      run: npx semantic-release
      env:
        GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }} 

    - name: Deploy to github pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GH_TOKEN }}
        BRANCH: master
        FOLDER: build