name: Teardown review env
on:
  pull_request:
    types: [closed]

jobs:
  delete-review-app:
    uses: Orfium/orfium-github-actions/.github/workflows/teardown-review-app.yml@master
    with:
      product: ictinus
      pr-number: ${{ github.event.pull_request.number }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
