name: Teardown review env
on:
  pull_request:
    types: [closed]

jobs:
  delete-review-app:
    uses: Orfium/orfium-github-actions/.github/workflows/teardown-frontend.yml@master
    secrets:
      REVIEW_TEARDOWN_TOKEN: ${{ secrets.REVIEW_TEARDOWN_TOKEN }}